const express = require('express')
const router = express.Router()

// module routers
const routerBanks = require('../components/banks/banksRouter')
const routerBanksUsers = require('../components/banksUsers/banksUsersRouter')
const routerNews = require('../components/news/newsRouter')
const routerRoles = require('../components/roles/rolesRouter')
const routerTasks = require('../components/tasks/tasksRouter')
const routerSession = require('../services/logged/loggedRouter')
// const routerSubscriptions = require('./routes/subscriptions')
// const routerUsers = require('./routes/users')
// const routerTypeMovement = require('./routes/typeMovement')
// const routerProfits = require('./routes/profits')
// const routerMovements = require('./routes/movements')
// const routerFiles = require('./routes/images')

router.use(routerBanks)
router.use(routerBanksUsers)
router.use(routerNews)
router.use(routerRoles)
router.use(routerTasks)
router.use(routerSession)
// router.use(routerFiles)
// router.use(routerSubscriptions)
// router.use(routerUsers)
// router.use(routerTypeMovement)
// router.use(routerProfits)
// router.use(routerMovements)
// router.use(mercadopagoRouter)
// router.use(emailRouter)

module.exports = router
